### ISSUE TITLE
Details focus state does not meet contrast requirements on inverted background

### ISSUE THREAD

**Issue by NickColley** [alphagov/focus-state-prototype#3]
<img width="414" alt="Screen Shot 2019-06-19 at 17 00 38" src="https://user-images.githubusercontent.com/2445413/59782443-ddd57300-92b5-11e9-8c33-f5f725958721.png">

**Comment by DebsDee** [comment]
Thanks, I've targeted the flash-card class here #https://github.com/alphagov/focus-state-prototype/commit/8a18ee7b95f6d78f3cf3faf2e4b9e6d668330d34

![Screen Shot 2019-06-21 at 14 30 27](https://user-images.githubusercontent.com/7225720/59925976-29605c00-9431-11e9-8a05-8cff66d7e663.png)
