### ISSUE TITLE
“Cancel passport” missing a link for passport interview

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/focus-state-prototype#4]
Page: https://apply-for-passport.herokuapp.com/cancel-passport

The fact that https://apply-for-passport.herokuapp.com/new-or-renew has a link makes me think the above page should have it as well

**Comment by DebsDee** [comment]
Good spot. I've add it here: #https://github.com/alphagov/focus-state-prototype/commit/c694075f53430ab33859d5e2f5c1dfa9d2cb64b2
