### ISSUE TITLE
Consider using Character count on "Is your passport damaged"

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/focus-state-prototype#5]
Feel free to ignore this one but it would be a good opportunity to test it.

Page https://apply-for-passport.herokuapp.com/damaged

**Comment by DebsDee** [comment]
@hannalaakso Added in #https://github.com/alphagov/focus-state-prototype/commit/15b545630b6edd64d169061800fae3c15441dfe3

**Comment by hannalaakso** [comment]
Looks good 👍It would be good to lower the character limit to 50 or so to ensure that some of the testers will go over the limit.
