### ISSUE TITLE
Use the country and territory autocomplete for collecting country name

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/focus-state-prototype#9]
https://apply-for-passport.herokuapp.com/apply-from-uk uses a select for choosing a country. This is possibly not accessible as the user either has to scroll down a long list of options until they see the country they want, or type in the first letter of the country and then scroll. 

We should probably use https://github.com/alphagov/govuk-country-and-territory-autocomplete instead.

**Comment by DebsDee** [comment]
Hi @hannalaakso I'm going to close this issue as the country selection option isn't part of the user journey for usability testing. Thanks for flagging it and good to know for future applications of the country select in prototypes.
